"""empty message

Revision ID: 9f5142cfb231
Revises: d5c9a3b03838
Create Date: 2022-08-06 19:58:13.566977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5142cfb231'
down_revision = 'd5c9a3b03838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.execute('UPDATE todolists set completed = FALSE WHERE completed IS NULL')
    op.alter_column('todolists', 'completed', nullable = False)
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todolists', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
               
    # ### end Alembic commands ###
